project/pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'
urlpatterns = [
    path('', views.index, name="index"), 
    path('reservar/', views.book, name="book"),
    path('cancelar/', views.cancel_book, name="cancel_book")
 ]

project/produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'
urlpatterns = [
    path('', views.index, name="index"), 
    path('<slug:category_slug>', views.index_category, name="index_category"),
    path('<slug:category_slug>/<slug:unit_slug>', views.view, name="view"),
    path('carrinho/', views.cart, name="cart"),
    path('adicionar-ao-carrinho/', views.add_to_cart, name="add_to_cart"),
    path('carrinho/incrementar/', views.increment_cart, name="increment_cart"),
    path('carrinho/decrementar/', views.decrement_cart, name="decrement_cart"),
    path('carrinho/limpar/', views.clean_cart, name="clean_cart"),
    path('carrinho/remover/', views.remove_from_cart, name="remove_from_cart")
 ]

project/usuario/urls.py
from django.urls import path
from . import views

app_name = 'usuario'
urlpatterns = [
    path('perfil/', views.profile, name="profile"),
    path('pagamentos/', views.payments, name="payments"),
    path('favoritos/', views.favorites, name="favorites"),
    path('favoritos/adicionar/', views.add_favorive, name="add_favorite"),
    path('favoritos/remover/', views.remove_favorive, name="remove_favorite")
 ]

project/templates/partials/_cart.html
{% load pipe %}

<div class="table-responsive">
    {% if request.session.cart %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Produto</th>        
                    <th>Quantidade</th>
                    <th>Preço</th>
                    <th>SubTotal</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for unit in request.session.cart.values %}
                    <tr>
                        <td class="fs-6">
                            <a  href="{% url 'produto:view' unit.slug %}?uid={{ unit.id }}">
                                {{ unit.name }}
                            </a>  
                        </td>
                    
                        <td class="fs-6">
                            <div class="d-flex justify-content-center">
                                {% if unit.quantity > 1 %}
                                    <a href="{% url 'produto:add_one_to_cart' unit.id %}?o=0">
                                        <button class="btn btn-outline-light" style="scale: .8;">
                                            <i class="fa-solid fa-minus" style="color: #9b9b9b;"></i>
                                        </button>
                                    </a>
                                {% endif %}
                                <span class="p-2">{{ unit.quantity }}</span>
                                <a href="{% url 'produto:add_one_to_cart' unit.id %}?o=1">
                                    <button class="btn btn-outline-light" style="scale: .8;">
                                        <i class="fa-solid fa-plus" style="color: #9b9b9b;"></i>
                                    </button>
                                </a>
                            </div>
                        </td>

                        <td class="fs-6">
                            R$ {{ unit.price|floatformat:2 }}
                        </td>

                        <td class="fs-6">R$ {{ unit.quantity_price|floatformat:2 }}</td>           
                        <td>
                            <button type="button" class="btn text-danger" title="Remover"
                                data-bs-toggle="modal" data-bs-target="#removeModal" 
                                data-unit-id="{{ unit.id }}" data-unit-name="{{ unit.name }}">
                                <i class="fa-solid fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>

            <div class="col-lg">   
                <tfoot>
                    <tr>
                        <td colspan="5">Total: <strong>R$ {{ request.session.cart|total_price_in_cart|floatformat:2 }}</strong></td>
                    </tr>
                </tfoot>
            </div>
        </table>
    {% else %}
        <p class="lead">Atualmente o seu Carrinho se encontra vazio.</p>
    {% endif %}
</div>

<div class="modal fade" id="removeModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Remover <span class="unit-name"></span>?</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
        </div>
        <div class="modal-body">
            <p>Tem certeza que deseja remover o produto "<span class="unit-name"></span>" do carrinho?</p>
        </div>
        <div class="modal-footer">
            <form action="{% url 'produto:remove_from_cart' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" id="unit-id" name="id" value="">
                <button type="submit" class="btn btn-danger">Sim</button>
            </form>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Não</button>
        </div>
        </div>
    </div>
</div>

project/templates/partials/_footer.html
<footer class="container-fluid bg-dark shadow mt-auto">
    <div class="row">
        <div class="col">
            <p class="lead text-light pt-2 fs-6">Aplicação desenvolvida em estilo E-commerce para facilitar o gerenciamento e interação do cliente em um negócio local.
                O sistema conta com três módulos principais: Produto, Pedido e Usuário, além de uma área administrativa para gerenciar cadastros e operações. </p>
        </div>
    </div>
    <p class="text-light lead fs-6">Ferramentas utilizadas: </p>
    <div class="row">
        <div class="col-6 col-md-3">
            <h4 class="text-light fs-5 text-center">Front End <br><small class="fs-6 fw-normal pb-2">(Interação visual)</small></h4>
            <ul>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://www.hostinger.com.br/tutoriais/o-que-e-html-conceitos-basicos" target="_blank">HTML</a></li>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://www.hostinger.com.br/tutoriais/o-que-e-css-guia-basico-de-css" target="_blank">CSS</a></li>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/First_steps/What_is_JavaScript" target="_blank">Javascript</a></li>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://getbootstrap.com/" target="_blank">Bootstrap</a></li>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://jquery.com/" target="_blank">jQuery</a></li>
            </ul>
        </div>
        <div class="col-6 col-md-3">
            <h4 class="text-light fs-5 text-center">Back End <br><small class="fs-6 fw-normal pb-2">(Interação de dados)</small></h4>
            <ul>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://djangoproject.com/" target="_blank">Django</a></li>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://www.django-rest-framework.org/" target="_blank">Django Rest Framework</a></li>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://www.postgresql.org/" target="_blank">PostgreSQL</a></li>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://dbeaver.io/about/" target="_blank">DBeaver</a></li>
            </ul>
        </div>
        <div class="col-6 col-md-3">
            <h4 class="text-light fs-5 text-center">DevOps <br><small class="fs-6 fw-normal pb-2">(Gerenciamento)</small></h4>
            <ul>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://git-scm.com/" target="_blank">Git</a></li>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://www.docker.com/" target="_blank">Docker</a></li>
            </ul>
        </div>
        <div class="col-6 col-md-3">
            <h4 class="text-light fs-5 text-center">Cloud <br><small class="fs-6 fw-normal pb-2">(Disponibilidade)</small></h4>
            <ul>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://aws.amazon.com/pt/ec2/" target="_blank">Amazon EC2</a></li>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://aws.amazon.com/pt/lambda/" target="_blank">AWS Lambda</a></li>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://aws.amazon.com/pt/rds/" target="_blank">Amazon RDS</a></li>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://aws.amazon.com/pt/s3/" target="_blank">Amazon S3</a></li>
                <li class="pb-2 lh-sm"><a class="text-light" href="https://aws.amazon.com/pt/sagemaker/" target="_blank">Amazon SageMaker</a></li>
            </ul>
        </div>
        <div class="col-md-4">
            <h4 class="text-light fs-5 text-center">Contato</h4>
            <address>
                <ul class="p-0 w-50 d-flex justify-content-evenly">
                    <li class="pb-2" title="Github">
                        <a class="text-light" href="https://github.com/matconi" target="_blank">
                            <i class="fa-brands fa-github fs-3"></i> 
                        </a>
                    </li>
                    <li class="pb-2 lh-sm" title="Linkedin">
                        <a class="text-light" href="#" target="_blank">
                            <i class="fa-brands fa-linkedin fs-3"></i>
                        </a>
                    </li>
                </ul>
            </address>
        </div>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

project/templates/partials/_head.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">

project/templates/partials/_messages.html
{% for message in messages %}
    <p class="alert {{ message.tags }}" role="alert">
        {{ message }}
    </p>
{% endfor %}

project/templates/partials/_nav.html
{% load produto_pipe %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}" title="Início">
            <h1 class="h1 fs-5">Gourmet Avenida</h1>
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" title="Produtos">
                        <span class="d-inline">Produtos</span>
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" href="{% url 'produto:index' %}">Todos</a>      
                        </li>
                        {% for category in categories %}
                            <li>
                                <a class="dropdown-item {% if category.slug == category_selected.slug %}active{% endif %}" href="{% url 'produto:index_category' category.slug %}">{{ category.name }}</a>      
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                {% if request.user.is_authenticated %}
                    {% if perms.usuario.favorites %}
                        <li title="Favoritos">
                            <a class="nav-link text-warning" href="{% url 'usuario:favorites' %}">
                                <i class="fa-solid fa-star"></i>
                                <span class="d-inline d-lg-none">Favoritos</span>
                            </a>
                        </li>
                    {% endif %}
                    <li class="nav-item dropdown">
                        <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" title="Perfil">
                            <i class="fa-solid fa-user"></i>
                            <span class="d-inline d-lg-none">Perfil</span>
                        </button>
                        <ul class="dropdown-menu">
                            <p class="lead text-center fs-6 fw-bold">{{ request.user.first_name }}
                                <hr class="w-75 m-auto"></p>
                                <li>
                                    <a class="dropdown-item" href="{% url 'usuario:profile' %}">Meu Perfil</a>
                                </li>
                                {% if perms.pedido.self_orders %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'pedido:index' %}">Pedidos</a>      
                                    </li>
                                {% endif %}
                                {% if perms.usuario.payments %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'usuario:payments' %}">Pagamentos</a>      
                                    </li>
                                {% endif %}
                            <li><a class="dropdown-item text-danger" href="{% url 'account_logout' %}">Sair</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Criar Conta</a>
                    </li>
                {% endif %}
                {% if perms.usuario.cart %}
                    <li class="nav-item">
                        <a class="nav-link nav-cart-link active" href="{% url 'produto:cart' %}">
                            <strong class="cart-count mr-1">{{ request.session.cart|total_in_cart }}x</strong>
                            <span class="nav-cart-icon mr-2">
                                <i class="fas fa-shopping-cart"></i>
                            </span>
                            <span class="d-inline d-lg-none">Carrinho</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

project/templates/partials/_pagination.html
<div class="container pt-4">
    <nav class="row">
        <ol class="pagination">
            {% if page_obj.has_previous %}
                <a href="?page=1" class="page-link">&laquo; Primeira</a>
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Anterior</a>
            {% endif %}
        
            {% for num in page_obj.paginator.page_range %}   
                {% if page_obj.number == num %}
                    <li class="page-item active">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="page-link">Próxima</a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">Última &raquo;</a>
            {% endif %}
        </ol>
        <span class="current lead fs-6">
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
        </span>
    </nav>
</div>