project/api/usuario/urls.py
from . import views
from django.urls import path

app_name = 'api_usuario'
urlpatterns = [
    path('load-more-favorites/', views.load_more_favorites, name='load_more_favorites')
]

project/pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'
urlpatterns = [
    path('', views.index, name="index"), 
    path('reservar/', views.book, name="book"),
    path('cancelar/', views.cancel_book, name="cancel_book")
 ]

project/usuario/auth/urls.py
from django.urls import path, re_path
from allauth.account import views
from allauth.socialaccount import views as sa_views
from usuario.auth import views as custom_views
from django.conf import settings
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from allauth.socialaccount.providers.google.provider import GoogleProvider

urlpatterns = [
    path("signup/", views.signup, name="account_signup"),
    path("login/", views.login, name="account_login"),
    path("logout/", custom_views.logout, name="account_logout"),
    path("inactive/", views.account_inactive, name="account_inactive"),
    path(
        "password/change/",
        views.password_change,
        name="account_change_password"
    ),
    path("password/set/", views.password_set, name="account_set_password"),
    # password reset
    path("password/reset/", views.password_reset, name="account_reset_password"),
    path(
        "password/reset/done/",
        custom_views.password_reset_done,
        name="account_reset_password_done"
    ),
    re_path(
        r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        views.password_reset_from_key,
        name="account_reset_password_from_key"
    ),
    path(
        "password/reset/key/done/",
        views.password_reset_from_key_done,
        name="account_reset_password_from_key_done"
    )
]

if settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += default_urlpatterns(GoogleProvider)
    urlpatterns += [
        path("social/connections/", sa_views.connections, name="socialaccount_connections"),
        path("login/error/", sa_views.login_error, name="socialaccount_login_error")
    ]

project/usuario/urls.py
from django.urls import path
from . import views

app_name = 'usuario'
urlpatterns = [
    path('perfil/', views.profile, name="profile"),
    path('pagamentos/', views.payments, name="payments"),
    path('favoritos/', views.favorites, name="favorites"),
    path('favoritos/adicionar/', views.add_favorive, name="add_favorite"),
    path('favoritos/remover/', views.remove_favorive, name="remove_favorite")
 ]

project/pedido/models/Order.py
from django.db import models
from django.utils import timezone
import decimal

class Order(models.Model):
    class Status(models.TextChoices):
        FINISHED = ('F', 'Finalizado',)
        BOOKED = ('B', 'Reservado',)
        EXPIRED = ('E', 'Expirado',)
        REPROVED = ('R', 'Reprovado',)
        CONSUMED = ('C', 'Consumido',)
        ABANDONED = ('A', 'Cancelado',)

    status = models.CharField("Status", max_length=1, choices=Status.choices, default=Status.FINISHED)
    date_time = models.DateTimeField("Data/Hora", default=timezone.now)
    booked_upto = models.DateTimeField("Reservado até", blank=True, null=True, default=None,
        help_text='Preencha apenas se estiver reservado'
    )

    total_price = models.DecimalField("Preço Total", max_digits=6, decimal_places=2, blank=True, default=0)
    total_quantity = models.PositiveIntegerField("Quantidade Total", blank=True, default=0)
    discount = models.DecimalField("Desconto", max_digits=6, decimal_places=2, default=0)

    customer = models.ForeignKey("usuario.Customer", on_delete=models.RESTRICT,
        verbose_name='Cliente'
    )
    payment = models.ForeignKey("usuario.Payment", on_delete=models.RESTRICT,
        blank=True, null=True, default=None, verbose_name='Pagamento'
    )

    def get_sold_price(self) -> float:
        return decimal.Decimal(self.total_price) - decimal.Decimal(self.discount)

    def set_total_price(self, order_units) -> float:
        self.total_price = sum([order_unit.quantity_price() for order_unit in order_units])

    def set_total_quantity(self, order_units) -> int:
        self.total_quantity = sum([order_unit.quantity for order_unit in order_units])

    def __str__(self) -> str:
        return f"Pedido {self.pk}"

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
        db_table = 'pedido_orders'
        ordering = ["-date_time"]
        permissions = [
            ("self_orders", "Can view self orders",),
            ("cancel_book", "Can cancel booking",)
        ]

project/usuario/models/Address.py
from django.db import models

class Address(models.Model):
    class State(models.TextChoices):
        ACRE = ('AC', 'Acre',)
        ALAGOAS = ('AL', 'Alagoas',)
        AMAPA = ('AP', 'Amapá',)
        AMAZONAS = ('AM', 'Amazonas',)
        BAHIA = ('BA', 'Bahia',)
        CEARA = ('CE', 'Ceará',)
        ESPIRITO_SANTO = ('ES', 'Espírito Santo',)
        GOIAS = ('GO', 'Goiás',)
        MARANHAO = ('MA', 'Maranhão',)
        MATO_GROSSO = ('MT', 'Mato Grosso',)
        MATO_GROSSO_DO_SUL = ('MS', 'Mato Grosso do Sul',)
        MINAS_GERAIS = ('MG', 'Minas Gerais',)
        PARA = ('PA', 'Pará',)
        PARAIBA = ('PB', 'Paraíba',)
        PARANA = ('PR', 'Paraná',)
        PERNAMBUCO = ('PE', 'Pernambuco',)
        PERNAMBUCO = ('PE', 'Pernambuco',)
        PIAUI = ('PI', 'Piauí',)
        RIO_DE_JANEIRO = ('PJ', 'Rio de Janeiro',)
        RIO_GRANDE_DO_NORTE = ('RN', 'Rio Grande do Norte',)
        RIO_GRANDE_DO_SUL = ('RS', 'Rio Grande do Sul',)
        RONDONIA = ('RO', 'Rondonia',)
        RORAIMA = ('RR', 'Roraima',)
        SANTA_CATARINA = ('SC', 'Santa Catarina',)
        SAO_PAULO = ('SP', 'São Paulo',)
        SERGIPE = ('SE', 'Sergipe',)
        TOCANTINS = ('TO', 'Tocantins',)

    cep = models.CharField("CEP", max_length=9)
    street = models.CharField("Rua", max_length=150)
    number = models.PositiveSmallIntegerField("Número")
    complement = models.CharField("Complemento", max_length=60, blank=True, null=True, default=None)
    city = models.CharField("Cidade", max_length=100)
    state = models.CharField("Estado", max_length=2, default=State.MINAS_GERAIS)

    customer = models.ForeignKey("Customer", on_delete=models.RESTRICT,
        verbose_name='Cliente'
    )

    def __str__(self) -> str:
        return self.street

    class Meta:
        abstract = True
        # verbose_name = 'Endereço'
        # verbose_name_plural = 'Endereços'
        # db_table = 'usuario_addresses'

project/usuario/models/Customer.py
from django.db import models
from produto.models.abstract.AbstractName import AbstractName
from django.contrib.auth.models import Group
from . import User
from usuario.domain.repositories import role_repository
from django.utils import timezone
from datetime import date
from usuario.domain.services import messages_service
from typing import List

class Customer(AbstractName):
    class Gender(models.TextChoices):
        MALE = ('M', 'Masculino')
        FEMALE = ('F', 'Feminino')

    bill = models.DecimalField("Conta", max_digits=6, decimal_places=2, default=0)
    limit = models.DecimalField("Limite", max_digits=6, decimal_places=2, default=0,
        help_text='Define o valor máximo da conta à prazo. Válido apenas para Usuários Premium.'
    )
    gender = models.CharField("Gênero", max_length=2, choices=Gender.choices)
    born_at = models.DateField("Nascimento")

    user = models.OneToOneField("User", on_delete=models.CASCADE,
        verbose_name='Usuário', related_name='user_customer', blank=True, null=True
    )
    favorites = models.ManyToManyField("produto.Unit", blank=True, verbose_name='Favoritos', related_name='unit_favorite')

    def get_age(self) -> int:
        today = date.today()
        age = today.year - self.born_at.year - ((today.month, today.day) < (self.born_at.month, self.born_at.day))
    
    def has_user(self) -> bool:
        return self.user is not None

    def is_premium(self) -> bool:
        return self.has_user() and self.user.has_perm('usuario.buy_in_term')

    @staticmethod
    def get_customer_roles_ids() -> List[int]:
        return [User.CUSTOMER_ROLE, User.CUSTOMER_PREMIUM_ROLE]

    def delete(self):
        if self.has_user():
            customer_roles_ids = Customer.get_customer_roles_ids()
            roles = role_repository.get_by_ids(customer_roles_ids)
            for role in roles:
                role_repository.remove(self.user, role)
        super(Customer, self).delete()

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        db_table = 'usuario_customers'
        permissions = [
            ("payments", "Can view self payments",),
            ("favorites", "Can view favorites",),
            ("add_favorite", "Can add favorite",),
            ("remove_favorite", "Can remove favorite",),
            ("buy_in_term", "Can buy in term",)
        ]

project/usuario/models/Payment.py
from django.db import models
from django.utils import timezone

class Payment(models.Model):
    class Method(models.TextChoices):
        MONEY = ('M', 'Dinheiro')
        PIX = ('P', 'Pix')
        CARD = ('C', 'Cartão')

    amount = models.DecimalField("Quantia", max_digits=5, decimal_places=2)
    method = models.CharField("Método", max_length=1, choices=Method.choices, default=Method.PIX)
    date_time = models.DateTimeField("Data/Hora", default=timezone.now)

    customer = models.ForeignKey("Customer", on_delete=models.RESTRICT, 
        verbose_name='Ciente'
    )

    def __str__(self) -> str:
        return f"Pagamento Nº {self.id}"

    class Meta:
        verbose_name = 'Pagamento'
        verbose_name_plural = 'Pagamentos'
        db_table = 'usuario_payments'
        ordering = ["-date_time"]

project/usuario/forms.py
from django import forms
from django.core.validators import ValidationError
from .models import User, Customer
from .domain.repositories import user_repository
from .domain.services import user_service
from usuario.auth.forms import phone_pattern

class ProfileForm(forms.ModelForm):
    email = forms.CharField(max_length=320, label='Email', required=True,
        help_text='Gmail obrigatório.<br>Pelo email, é possível entrar com um clique pelo Google,'
        ' recuperar senhas e ter um canal de contato.',
        widget=forms.TextInput(
            attrs={
                "placeholder": "exemplo@gmail.com"
            }
        )
    )
    first_name = forms.CharField(max_length=50, label='Primeiro nome', required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Primeiro nome"
            }
        )
    )
    last_name = forms.CharField(max_length=120, label='Último nome', required=False, 
        widget=forms.TextInput(
            attrs={
                "placeholder": "Último nome(opcional)"
            }
        )
    )
    phone = forms.CharField(max_length=14, label='Celular', required=True,
        help_text='Digite apenas números.<br>Com o número de telefone podemos identificá-lo(a) mais facilmente'
        ' e estabelecer<br> uma comunicação mais direta.',
        validators=[phone_pattern()],
        widget=forms.TextInput(
            attrs={
                "placeholder": "(12)12345-1234",
                "class": "w-50 cel-input"
            }
        )
    )
    gender = forms.ChoiceField(choices=Customer.Gender.choices, label='Gênero')
    born_at = forms.DateField(input_formats=['%d/%m/%Y'], label='Data de nascimento', required=True,
        widget=forms.DateInput(
            attrs={
                "placeholder": "DD/MM/AAAA",
                "class": "date-input"
            }
        )
    )

    def clean_email(self):
        email = self.cleaned_data.get('email')  
        if email != self.instance.email:
            user_service.email_in_use(email)

        user_service.gmail_required(email)
        return email

    def save(self):
        user = super(ProfileForm, self).save()
        if user.is_customer():
            customer = user.user_customer
            customer.gender = self.cleaned_data["gender"]
            customer.born_at = self.cleaned_data["born_at"]
            customer.save()
        return user

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone',) 

project/api/usuario/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.contrib.auth.decorators import login_required, permission_required
from rest_framework import status
from .serializers import FavoritesSerializer
from produto.domain.repositories import unit_repository
from produto.models import Unit
from produto.domain.services import unit_service

@api_view(['GET'])
@login_required
@permission_required('usuario.favorites')
def load_more_favorites(request):
    offset = int(request.GET.get('offset', 0))
    
    kwargs = unit_service.filter_units(request)

    units = unit_repository.get_customer_favorites(request.user.user_customer, kwargs)[offset:offset + unit_repository.CARDS_PER_VIEW]

    serializer = FavoritesSerializer(units, many=True)
    response_data = {
        "added_units": len(serializer.data),
        "units": serializer.data
    }

    return Response(response_data, status=status.HTTP_200_OK)

project/usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from .forms import ProfileForm
from .domain.services import messages_service, user_service
from pedido.domain.repositories import order_unit_repository
from produto.domain.repositories import unit_repository
from gourmetavenida.utils import paginate
from .domain.services import payment_service
from .domain.repositories import payment_repository, user_repository, customer_repository
from django.http import JsonResponse
from django.urls import reverse
from django.views.decorators.http import require_GET, require_POST, require_http_methods

@require_http_methods(['GET', 'POST'])
@login_required
def profile(request):
    user = request.user
    context = {"user": user}
    if request.method == 'GET':
        form = ProfileForm(
            initial={
                "email": user.email,
                "first_name": user.first_name,
                "last_name": user.last_name,
                "phone": user.phone,
            }
        )
        user_service.fill_customer_initial(user, form)
        context.update({"form": form})

        return render(request, "usuario/profile.html", context)
    elif request.method == 'POST':
        form = ProfileForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages_service.updated_profile(request)
        context.update({"form": form})

        return render(request,"usuario/profile.html", context)

@require_GET
def home(request):
    week_trends = order_unit_repository.get_week_trends()
    releases = unit_repository.get_releases()
    
    json_data = {
        "urls": {
            "add_to_cart": reverse('produto:add_to_cart')
        }
    }

    context = {
        "week_trends": week_trends,
        "releases": releases,
        "json_data": json_data
    }

    if request.user.is_customer():
        again = order_unit_repository.get_again(request.user.user_customer)
        context["again"] = again

    return render(request, 'usuario/home.html', context)

@require_GET
@login_required
@permission_required('usuario.payments', raise_exception=True)
def payments(request):
    kwargs = payment_service.filter_payments(request)

    payments = payment_repository.get_customer_payments(request.user.user_customer, kwargs)

    context = {
        "page_obj": paginate(request, payments)
    }
    return render(request, 'usuario/payments.html', context)

@require_GET
@login_required
@permission_required('usuario.favorites', raise_exception=True)
def favorites(request):
    units = unit_repository.get_customer_favorites(request.user.user_customer)
    units_loaded = units[0:unit_repository.CARDS_PER_VIEW]

    json_data = {
        "urls": {
            "load_more": reverse('api_usuario:load_more_favorites'),
            "add_to_cart": reverse('produto:add_to_cart')
        },
        "permissions": {
            "add_to_cart": request.user.has_perm('produto.add_to_cart')
        }
    }

    context = {
        "units_loaded": units_loaded, 
        "json_data": json_data
    }
    return render(request, 'usuario/favorites.html', context)

@require_POST
@login_required
@permission_required('usuario.add_favorite', raise_exception=True)
def add_favorive(request):
    unit_id = request.POST.get('id')

    unit = unit_repository.get_or_404(unit_id)
    customer_repository.add_favorite(request.user.user_customer, unit)

    messages = {
        "success": [messages_service.favorite_added(unit)],
    }
    return JsonResponse(
        {"messages": messages}
    )

@require_POST
@login_required
@permission_required('usuario.remove_favorite', raise_exception=True)
def remove_favorive(request):
    unit_id = request.POST.get('id')

    unit = unit_repository.get_or_404(unit_id)
    customer_repository.remove_favorite(request.user.user_customer, unit)

    messages = {
        "success": [messages_service.favorite_removed(unit)],
    }
    return JsonResponse(
        {"messages": messages}
    )

project/usuario/templates/usuario/home.html
{% extends 'base.html' %}
{% load static %}
{% load usuario_pipe %}

{% block head %}
    <title>Início | Gourmet Avenida</title>
    <!-- carousel source credit: https://www.codingnepalweb.com/draggable-card-slider-html-css-javascript/ -->
    <link rel="stylesheet" href="{% static 'css/product-carousel.css' %}"></link>
{% endblock head %}

{% block main %}
    {% if perms.usuario.buy_in_term %}
        <header>
            <div class="container">
                <p class="lead fs-4 text-center">
                    Olá, <strong>{{ request.user.first_name }}</strong>, atualmente a sua conta é:<br>
                    <strong class="fs-1">{{ request.user.user_customer.bill|get_bill }}</strong><br>
                    <a class="fs-6 text-secondary nav-link pt-2 d-inline" href="{% url 'usuario:payments' %}">
                        Ver pagamentos
                    </a>
                </p>
            </div>
        </header>
    {% endif %}

    <section>
        <h1>Em Alta</h1>
        {% if week_trends %}
            <p class="lead">Os {{ week_trends|length }} mais vendidos da semana.</p>
            <div class="trends-wrapper">
                {% if week_trends|length > 2 %}
                    <i id="left" class="arrow fa-solid fa-angle-left"></i>
                {% endif %}
                <ul class="trends-carousel">
                    {% for unit in week_trends %}
                        <li class="trends-card">
                            <p class="m-2"><span class="fw-bold ">{{ forloop.counter }}°</span> <small class="float-end">{{ unit.total_sold }} vendido(s)</small></p>
                            {% include 'components/product_card.html' %}
                        </li>
                    {% endfor %}
                </ul>
                {% if week_trends|length > 2 %}
                    <i id="right" class="arrow fa-solid fa-angle-right"></i>
                {% endif %}
            </div>
        {% else %}
            <p class="lead">Nenhum produto vendido na semana.</p>
        {% endif %}
    </section>

    <section>
        <h1>Novo</h1>
        {% if releases %}
            <p class="lead">Os {{ releases|length }} lançados no último mês.</p>
            <div class="releases-wrapper">
                {% if releases|length > 2 %}
                    <i id="left" class="arrow fa-solid fa-angle-left"></i>
                {% endif %}
                <ul class="releases-carousel">
                    {% for unit in releases %}
                        <li class="releases-card">
                            {% include 'components/product_card.html' %}
                        </li>
                    {% endfor %}
                </ul>
                {% if releases|length > 2 %}
                    <i id="right" class="arrow fa-solid fa-angle-right"></i>
                {% endif %}
            </div>
        {% else %}
            <p class="lead">Nenhum produto lançado no último mês.</p>
        {% endif %}
    </section>

    {% if perms.pedido.add_order %}
        <section>
            <h1>Aproveitar Novamente</h1>
            {% if again %}
                <p class="lead">Os {{ again|length }} mais consumidos por você nos últimos 45 dias.</p>
                <div class="again-wrapper">
                    {% if again|length > 2 %}
                        <i id="left" class="arrow fa-solid fa-angle-left"></i>
                    {% endif %}
                    <ul class="again-carousel">
                        {% for unit in again %}
                            <li class="again-card">
                                {% include 'components/product_card.html' %}
                            </li>
                        {% endfor %}
                    </ul>
                    {% if again|length > 2 %}
                        <i id="right" class="arrow fa-solid fa-angle-right"></i>
                    {% endif %}
                </div>
            {% else %}
                <p class="lead">Nenhum produto consumido por você nos últimos 45 dias.</p>
            {% endif %}
        </section>
    {% endif %}

    <div class="position-fixed bottom-0 end-0 m-1" id="toast-container" style="z-index: 11">
    </div>
{% endblock main %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/produto/product-carousel.js' %}"></script>
    {{ json_data|json_script:"json-data" }}
    {% if perms.produto.add_to_cart %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script type="text/javascript" src="{% static 'js/shared.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/produto/index-forms.js' %}"></script>
    {% endif %}
{% endblock scripts %}

project/usuario/templates/usuario/payments.html
{% extends 'base.html' %}
{% load static %}
{% load produto_pipe %}
{% block head %}
    <title>Pagamentos | Gourmet Avenida</title>
{% endblock head %}

{% block main %}
    <div class="row mt-3">
        <div class="col">
            <h2>Pagamentos</h2>
            <div class="accordion mb-2" id="accordion-filter">
                <div class="accordion-item">
                    <h4 class="accordion-header " id="headingFilter">
                        <button class="accordion-button collapsed bg-transparent" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-filter" aria-expanded="true" aria-controls="collapseFilter">
                            <i class="fa-solid fa-filter"></i> Filtros
                        </button>
                    </h4>
                    <div id="collapse-filter" class="accordion-collapse collapse" aria-labelledby="headingFilter" data-bs-parent="#accordion-filter">
                        <div class="accordion-body">
                            <form id="filter-form" action="" method="GET">
                                <div class="row">
                                    <div class="col mt-2">
                                        <label for="start-date" class="form-label">De:</label>
                                        <div class="input-group">
                                            <input type="text" class="form-control date-input" name="start_date" id="start-date" placeholder="DD/MM/AAAA" value="{{ request.GET.start_date }}">
                                            <button class="btn btn-sm btn-outline-primary" type="button" id="copy-date" title="Mesmo dia">
                                                <i class="fa-solid fa-clone"></i>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="col mt-2">
                                        <label for="end-date" class="form-label">Até:</label>
                                        <input type="text" class="form-control date-input" name="end_date" id="end-date" placeholder="DD/MM/AAAA" value="{{ request.GET.end_date }}">
                                    </div>
                                    <div class="col mt-2">
                                        <label for="method" class="form-label">Método</label>
                                        <select name="method" id="method" class="form-select">
                                            <option value="">Todos</option>
                                            <option value="P" {% if request.GET.method == 'P' %}selected{% endif %}>Pix</option>
                                            <option value="M" {% if request.GET.method == 'M' %}selected{% endif %}>Dinheiro</option>
                                            <option value="C" {% if request.GET.method == 'C' %}selected{% endif %}>Cartão</option>
                                        </select>
                                    </div>       
                                </div>
                                <button class="btn btn-primary w-25 mt-3" id="filter-btn" type="submit">Filtrar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <section>
                {% if page_obj %}
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Valor</th>
                                    <th>Data</th>
                                    <th>Método</th>
                                    <th>ID</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for payment in page_obj %}            
                                    <tr>
                                        <td class="fs-6">
                                            {{ payment.amount|currencyformat }}
                                        </td>
                                        <td class="fs-6">
                                            {{ payment.date_time.date }}
                                        </td>
                                        <td class="fs-6">
                                            {{ payment.get_method_display }}
                                        </td>
                                        <td class="fs-6">
                                            {{ payment.id }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <p class="lead">
                        Nenhum pagamento encontrado.
                    </p>
                {% endif %}
            </section>
            {% if page_obj %}
                {% include 'partials/_pagination.html' %}
            {% endif %}
        </div>       
    </div>
{% endblock main %}

{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript" src="{% static 'js/shared.js' %}"></script>
{% endblock scripts %}

project/usuario/templates/usuario/profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
    <title>Meu perfil | Gourmet Avenida</title>
{% endblock head %}

{% block main %}
    <div class="row">
        <div class="col-lg mt-3">
            <h1>Meu Perfil</h1> 
            <form method="POST" action="" class="mb-4">
                {% csrf_token %}
                <fieldset>
                    <legend>Usuário</legend>
                    {{ form.email|as_crispy_field }}
                    {{ form.first_name|as_crispy_field }}
                    {{ form.last_name|as_crispy_field }}
                    {{ form.phone|as_crispy_field }}
                </fieldset>
                {% if user.user_customer %}
                    <fieldset>
                        <legend>Cliente</legend>
                        <div class="row">
                            <div class="col-6">{{ form.gender|as_crispy_field }}</div>
                            <div class="col-6">{{ form.born_at|as_crispy_field }}</div>
                        </div>
                    </fieldset>
                {% endif %}
                <button type="submit" class="btn btn-success">Salvar</button>
            </form> 
            <div class="d-block d-md-inline">
                <a href="{% url 'socialaccount_connections' %}" class="text-decoration-none">
                    <button class="btn btn-outline-secondary m-2">
                        Contas Sociais
                    </button>
                </a>
                {% if perms.pedido.self_orders %}
                    <a href="{% url 'pedido:index' %}"class="text-decoration-none">
                        <button class="btn btn-outline-primary m-2">
                            Pedidos
                        </button>
                    </a>
                {% endif %}
                {% if perms.usuario.favorites %}
                    <a href="{% url 'usuario:favorites' %}"class="text-decoration-none">
                        <button class="btn btn-outline-warning m-2">
                            <i class="fa-solid fa-star"></i>
                            Favoritos
                        </button>
                    </a>
                {% endif %}
                <a href="{% url 'account_change_password' %}" class="text-decoration-none">
                    <button class="btn btn-outline-danger m-2">
                        <i class="fa-solid fa-key"></i>
                        Alterar Senha
                    </button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript" src="{% static 'js/shared.js' %}"></script>
{% endblock scripts %}