project/pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'
urlpatterns = [
    path('', views.index, name="index"), 
    path('reservar/', views.book, name="book"),
    path('cancelar/', views.cancel_book, name="cancel_book")
 ]

project/produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'
urlpatterns = [
    path('', views.index, name="index"), 
    path('<slug:category_slug>', views.index_category, name="index_category"),
    path('<slug:category_slug>/<slug:unit_slug>', views.view, name="view"),
    path('carrinho/', views.cart, name="cart"),
    path('adicionar-ao-carrinho/', views.add_to_cart, name="add_to_cart"),
    path('carrinho/incrementar/', views.increment_cart, name="increment_cart"),
    path('carrinho/decrementar/', views.decrement_cart, name="decrement_cart"),
    path('carrinho/limpar/', views.clean_cart, name="clean_cart"),
    path('carrinho/remover/', views.remove_from_cart, name="remove_from_cart")
 ]

project/pedido/models/Order.py
from django.db import models
from django.utils import timezone
import decimal

class Order(models.Model):
    class Status(models.TextChoices):
        FINISHED = ('F', 'Finalizado',)
        BOOKED = ('B', 'Reservado',)
        EXPIRED = ('E', 'Expirado',)
        REPROVED = ('R', 'Reprovado',)
        CONSUMED = ('C', 'Consumido',)
        ABANDONED = ('A', 'Cancelado',)

    status = models.CharField("Status", max_length=1, choices=Status.choices, default=Status.FINISHED)
    date_time = models.DateTimeField("Data/Hora", default=timezone.now)
    booked_upto = models.DateTimeField("Reservado até", blank=True, null=True, default=None,
        help_text='Preencha apenas se estiver reservado'
    )

    total_price = models.DecimalField("Preço Total", max_digits=6, decimal_places=2, blank=True, default=0)
    total_quantity = models.PositiveIntegerField("Quantidade Total", blank=True, default=0)
    discount = models.DecimalField("Desconto", max_digits=6, decimal_places=2, default=0)

    customer = models.ForeignKey("usuario.Customer", on_delete=models.RESTRICT,
        verbose_name='Cliente'
    )
    payment = models.ForeignKey("usuario.Payment", on_delete=models.RESTRICT,
        blank=True, null=True, default=None, verbose_name='Pagamento'
    )

    def get_sold_price(self) -> float:
        return decimal.Decimal(self.total_price) - decimal.Decimal(self.discount)

    def set_total_price(self, order_units) -> float:
        self.total_price = sum([order_unit.quantity_price() for order_unit in order_units])

    def set_total_quantity(self, order_units) -> int:
        self.total_quantity = sum([order_unit.quantity for order_unit in order_units])

    def __str__(self) -> str:
        return f"Pedido {self.pk}"

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
        db_table = 'pedido_orders'
        ordering = ["-date_time"]
        permissions = [
            ("self_orders", "Can view self orders",),
            ("cancel_book", "Can cancel booking",)
        ]

project/pedido/models/OrderUnit.py
from django.db import models

class OrderUnit(models.Model):
    quantity = models.PositiveIntegerField("Quantidade", default=1)
    price = models.DecimalField("Preço", max_digits=6, decimal_places=2, blank=True)

    order = models.ForeignKey("Order", on_delete=models.CASCADE,
        verbose_name='Pedido', related_name='order_units'
    )
    unit = models.ForeignKey("produto.Unit", on_delete=models.RESTRICT,
        verbose_name='Unidade'
    )
    
    def __str__(self) -> str:
        return f"Item {self.pk}"

    def quantity_price(self) -> float:
        return float(self.price * self.quantity)

    def save(self, **kwargs):
        self.price = self.price or self.unit.price
        return super(OrderUnit, self).save()

    class Meta:
        verbose_name = 'Item do Pedido'
        verbose_name_plural = 'Itens do Pedido'
        db_table = 'pedido_order_units'

project/pedido/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from .domain.services import OrderService
from .domain.repositories import order_repository, order_unit_repository
from produto.domain.repositories import unit_repository
from django.contrib.auth.decorators import login_required, permission_required
from gourmetavenida.utils import paginate, is_ajax
from django.views.decorators.http import require_GET, require_POST
from django.http import JsonResponse
from gourmetavenida.utils import refresh_if_invalid, reload_if_invalid
from produto.templatetags import produto_pipe

@require_GET
@login_required
@permission_required('pedido.self_orders', raise_exception=True)
def index(request):
    kwargs = OrderService.filter_orders(request)

    orders = order_repository.get_user_orders(request.user, kwargs)

    context = {
        "page_obj": paginate(request, orders),
    }

    return render(request, 'pedido/index.html', context)

@require_POST
@login_required
@permission_required('pedido.add_order', raise_exception=True)
def book(request):
    cart = request.session.get('cart')  
    units_ids = [unit_id for unit_id in cart]  

    order_service = OrderService(request)
    refresh_if_invalid(order_service, order_service.book, [units_ids])
    messages = order_service.get_messages()
    refresh_cart = request.session.get('cart')

    return JsonResponse({
        "messages": messages,
        "refresh_cart": {
            "cart": refresh_cart,
            "total_in_cart": produto_pipe.total_in_cart(refresh_cart),
            "total_price_in_cart": produto_pipe.total_price_in_cart(refresh_cart)
        }
    })

@require_POST
@login_required
@permission_required('pedido.cancel_book', raise_exception=True)
def cancel_book(request):
    id_param = request.POST.get('id')

    order_service = OrderService(request)
    reload_if_invalid(request, order_service, order_service.cancel_book, [id_param])

    return redirect('pedido:index')

project/pedido/templates/pedido/index.html
{% extends 'base.html' %}
{% load static %}
{% load produto_pipe %}
{% block head %}
    <title>Pedidos | Gourmet Avenida</title>
{% endblock head %}

{% block main %}
    <div class="row mt-3">
        <div class="col">
            <h2>Pedidos</h2>
            <div class="accordion mb-2" id="accordion-filter">
                <div class="accordion-item">
                    <h4 class="accordion-header " id="headingFilter">
                        <button class="accordion-button collapsed bg-transparent" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-filter" aria-expanded="true" aria-controls="collapseFilter">
                            <i class="fa-solid fa-filter"></i> Filtros
                        </button>
                    </h4>
                    <div id="collapse-filter" class="accordion-collapse collapse" aria-labelledby="headingFilter" data-bs-parent="#accordion-filter">
                        <div class="accordion-body">
                            <form id="filter-form" action="" method="GET">
                                <div class="row">
                                    <div class="col mt-2">
                                        <label for="unit" class="form-label">Produto</label>
                                        <input type="text" class="form-control" name="unit" id="unit" placeholder="Pesquisar..." value="{{ request.GET.unit }}">
                                        <label for="start-date" class="form-label">De:</label>
                                        <div class="input-group">
                                            <input type="text" class="form-control date-input" name="start_date" id="start-date" placeholder="DD/MM/AAAA" value="{{ request.GET.start_date }}">
                                            <button class="btn btn-sm btn-outline-primary" type="button" id="copy-date" title="Mesmo dia">
                                                <i class="fa-solid fa-clone"></i>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="col mt-2">
                                        <label for="status" class="form-label">Status</label>
                                        <select name="status" id="status" class="form-select">
                                            <option value="">Todos</option>
                                            <option value="F" {% if request.GET.status == 'F' %}selected{% endif %}>Finalizado</option>
                                            <option value="B" {% if request.GET.status == 'B' %}selected{% endif %}>Reservado</option>
                                            <option value="E" {% if request.GET.status == 'E' %}selected{% endif %}>Expirado</option>
                                            <option value="R" {% if request.GET.status == 'R' %}selected{% endif %}>Reprovado</option>
                                        </select>
                                        <label for="end-date" class="form-label">Até:</label>
                                        <input type="text" class="form-control date-input" name="end_date" id="end-date" placeholder="DD/MM/AAAA" value="{{ request.GET.end_date }}">
                                    </div>
                                </div>
                                <button class="btn btn-primary w-25 mt-3" id="filter-btn" type="submit">Filtrar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <section>
                <div class="accordion pb-2" id="accordion">
                    {% for order in page_obj %}
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingOne">
                                <button class="accordion-button collapsed bg-transparent" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{ order.id }}" aria-expanded="true" aria-controls="collapseOne">
                                    <div class="p-2">
                                        {% if order.status == 'F' %}
                                            <span class="badge bg-success" title="Pedido finalizado">
                                                <i class="fa-regular fa-circle-check"></i>
                                                {{ order.get_status_display }}
                                            </span>
                                        {% elif order.status == 'B' %}
                                            <span class="badge bg-primary" title="Pedido reservado">
                                                <i class="fa-solid fa-book-bookmark"></i>
                                                {{ order.get_status_display }}
                                            </span>
                                        {% elif order.status == 'E' %}
                                            <span class="badge bg-warning" title="Pedido expirado">
                                                <i class="fa-solid fa-triangle-exclamation"></i>
                                                {{ order.get_status_display }}
                                            </span>
                                        {% else %}
                                            <span class="badge bg-danger" title="Pedido reprovado">
                                                <i class="fa-solid fa-circle-xmark"></i>
                                                {{ order.get_status_display }}
                                            </span>
                                        {% endif %}
                                    </div>
                                    <caption>{{ order.date_time.date }} <strong class="m-1">{{ order|actual_order_price|currencyformat }}</strong></caption>
                                </button>
                            </h2>
                            <div id="collapse-{{ order.id }}" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordion">
                                <div class="accordion-body">
                                    <div class="table-responsive">
                                        <table class="table table-hover">
                                            # <strong>{{ order.id }}</strong>
                                            {% if order.status == 'B' %}
                                                {% if perms.pedido.cancel_book %}
                                                    <button type="button" class="btn btn-danger float-end" data-bs-toggle="modal" data-bs-target="#cancelModal"
                                                    data-order-id="{{ order.id }}">Cancelar</button>
                                                {% endif %}
                                                <p class="lead fs-6 d-inline m-0 float-end p-2">Até {{ order.booked_upto.date }}</p>
                                            {% endif %}
                                            <thead>
                                                <tr>
                                                    <th>Produto</th>
                                                    <th>Quantidade</th>
                                                    <th>Preço</th>
                                                    <th>Subtotal</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for order_unit in order.order_units.all %}
                                                    <tr>
                                                        <td class="fs-6">
                                                            <a href="{% url 'produto:view' order_unit.unit.product.category.slug order_unit.unit.product.slug %}?uid={{ order_unit.unit.id }}">
                                                                {{ order_unit.unit.name }}
                                                            </a>
                                                        </td>
                                                        <td class="fs-6">
                                                            <div class="d-flex justify-content-center">
                                                                <span class="p-2">{{ order_unit.quantity }}</span>
                                                            </div>
                                                        </td>
                                                        <td class="fs-6">
                                                            {{ order_unit.unit.price|currencyformat }}
                                                        </td>
                                                        <td class="fs-6">
                                                            {{ order_unit.quantity_price|currencyformat }}
                                                        </td>
                                                    </tr>
                                                {% empty %}
                                                    <p class="lead">
                                                        Nenhum item relacionado ao pedido.
                                                    </p>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                        {% if order.discount > 0 %}
                                            Desconto: <strong>{{ order.discount|currencyformat }}</strong>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <p class="lead">
                            Nenhum pedido encontrado.
                        </p>
                    {% endfor %}
                </div>
            </section>
            {% if page_obj %}
                {% include 'partials/_pagination.html' %}
            {% endif %}
        </div>       
    </div>

    <div class="modal fade" id="cancelModal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Cancelar pedido?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
            </div>
            <div class="modal-body">
                <p>Tem certeza que deseja cancelar o pedido de reserva?</p>
            </div>
            <div class="modal-footer">
                <form action="{% url 'pedido:cancel_book' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" id="order-id" name="id" value="">
                    <button type="submit" class="btn btn-danger">
                        Sim
                    </button>
                </form>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Não</button>
            </div>
            </div>
        </div>
    </div>
{% endblock main %}

{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript" src="{% static 'js/shared.js' %}"></script>
    {% if perms.pedido.cancel_book %}
        <script type="text/javascript" src="{% static 'js/pedido/index-modal.js' %}"></script>
    {% endif %}
{% endblock scripts %}